### ISSUE TITLE
Feature Request: Support csproj

### ISSUE THREAD

**Issue by AdenFlorian** [jchannon/csharpextensions#19]
I believe the newer versions of .NET Core are moving away from the project.json and back to .csproj files. From what I've read, some parts of this extension only work with project.json projects. It would be nice to have those features work with csproj projects as well. One feature that I know of that only work with project.json is the "New C# Class" command.

**Comment by jchannon** [comment]
That should be quiet a simple PR if you fancy it. Just need to tell the
extension to look for project.json or *.csproj

It already does the former.

Let me know what you think

**Comment by AdenFlorian** [comment]
Yup, working on it now :)

On Fri, Jan 27, 2017 at 12:08 PM, Jonathan Channon <notifications@github.com
