### ISSUE TITLE
Stopped Working

### ISSUE THREAD

**Issue by CMTietgen** [jchannon/csharpextensions#28]
VS Code Version: 1.12.1

**Extensions and Versions**

C#: 1.9.0
C# Extensions: 1.3.0

I'm not sure what happened, but something seems to have stopped working.

When I type **ctor** or **prop** and press tab, sometimes a tab is inserted and sometimes something else. For example, if I type **ctor** and press tab, is inserts the word Controller.

I've removed all extensions except this one and C# by Microsoft and it still doesn't work.

I don't even see ctor in Intellisense, like your screenshot shows.

Thoughts?

**Comment by jchannon** [comment]
ctor comes from the C# plugin. i have heard about this from a friend but
usually a reboot etc solves it. unfortunately not this extension to blame.
sorry

**Comment by CMTietgen** [comment]
I was thinking it was this extension since your screenshots showed the **ctor** completion snippet. A reboot didn't help. Guess I'll have to keep looking. Thanks.

**Comment by jchannon** [comment]
I just update to latest VSCode and something is definitely not right with these snippets. Have to manually invoke intellisense via keyboard shortcuts to get them to work properly

**Comment by CMTietgen** [comment]
It's apparently an issue with the C# extension by Microsoft/omnisharp and should be fixed in the 1.10 release.

https://github.com/OmniSharp/omnisharp-vscode/issues/1459
https://github.com/OmniSharp/omnisharp-vscode/issues/1462

**Comment by jchannon** [comment]
Cool, thanks
