### ISSUE TITLE
Request - great extension

### ISSUE THREAD

**Issue by CoderJason123** [jchannon/csharpextensions#41]
You've done a nice job.  Would you consider the following request?  Perhaps it's something if it's not easy to do that I can assist.

On add field from constructor, a good practice is to use _fieldName instead of without the underscore.  Additionally, using "this." is not a coding practice everyone uses.  Perhaps this is as simple as a configuration setting on "use underscore" on fields, and "don't use this" when possible.  You have to when of course the field matches the parameter name exactly.

Thoughts?

**Comment by jchannon** [comment]
I'm no longer maintaining the project but I believe the this/underscore is
an option in the plugin
