### ISSUE TITLE
Can create invalid namespace

### ISSUE THREAD

**Issue by hoetz** [jchannon/csharpextensions#7]
Example:

namespace Foo-Bar
{
    public class newclass
    {
        
    }
}

**Comment by jchannon** [comment]
I assume your path is /Projects/Foo-Bar ?

What should the namespace be in that situation?

**Comment by hoetz** [comment]
IIRC Visual Studio replaces "-" with "_"

**Comment by jchannon** [comment]
If you can confirm I'll make the change :)

**Comment by hoetz** [comment]
Confirmed.

**Comment by hoetz** [comment]
FWIW this is the spec :)
https://msdn.microsoft.com/en-us/library/aa664670.aspx

**Comment by jchannon** [comment]
<img width="762" alt="screen shot 2016-10-17 at 09 23 53" src="https://cloud.githubusercontent.com/assets/105126/19430280/93f84a16-944b-11e6-89b2-03a60c51a380.png">

How's this?

Ooh a spec, will take a look, thanks

**Comment by hoetz** [comment]
:shipit:

**Comment by jchannon** [comment]
🚢 'ed

**Comment by jchannon** [comment]
Thanks for the report
