### ISSUE TITLE
Cant create new c# class or interface

### ISSUE THREAD

**Issue by Mkayxx** [jchannon/csharpextensions#9]
When i press new class or new interface nothing happens.Do i need to do something else before i press create new c# class?

**Comment by Mkayxx** [comment]
When i press new class or new interface nothing happens.Do i need to do something else before i press create new c# class?

**Comment by jchannon** [comment]
Are you using it in a project json project. If not this won't work

**Comment by Mkayxx** [comment]
how do i use it in a json project ? do i need to create it? im confused.

**Comment by jchannon** [comment]
This extension only works for a dotnet core project. That type of project
has a project.json file as the project file which contains the packages and
meta data about the project you are working on. To get started visit dot.net

**Comment by Mkayxx** [comment]
ok thanks
